permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
gems:
  [jekyll-paginate]
# 作者信息
author: 
  name: zhangshuai
  email: tozhangshuai@qq.com
  link: http://meiyou.com
  weibo: http://weibo.com/lovezhangshuai
  github: https://github.com/zhangshuai110
  music: http://meiyou.com
  linkedin: https://meiyou.com

# 站点信息
title: 张帅
description: 张帅
url: http://zhangshuai110.github.io/docs/
rss_url: /pages/atom.xml
address: docs/

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id:  
  url: 

# disqus 设置
disqus:
  shortname: zhangshuai

# 主题设置，自动激活某个标签
active: 笔记

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档